# Generated by Django 2.2.24 on 2022-08-14 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_auto_20181031_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='speciality',
            field=models.ForeignKey(max_length=4000, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.Speciality'),
        ),
    ]
